version: '3.8'

services:
  yagami-bot:
    build: .
    container_name: yagami-vps-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ~/.ssh:/root/.ssh:ro  # Mount SSH keys (read-only)
    network_mode: host
    environment:
      - TZ=UTC
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
